### PR TITLE
Introduced PHPUnit tests + Show message about curl and firewall [Delivers #88308382]

### PR DESCRIPTION
**Pull request by Petervw**
This PR contains:
- Introduced PHPUnit testing with doubles;
- Show a message when the API host is unavailable;
- Show a message when the curl version is below 7.20.0; 
- Codestyle;

### CODE REVIEW

**Comment by omarreiss** [comment]
CR :heavy_check_mark:

**Comment by omarreiss** [comment]
@jdevalk please merge if you agree with these changes.

**Comment by jdevalk** [comment]
Done.

**Comment by jdevalk** [comment]
Pinging @dannyvankooten to let him know as well :)

**Comment by Petervw** [comment]
:+1:

**Pull request merged**
