### PR TITLE
Improve l10n strings

### LINKED ISSUE #66: Improve variables for better l10n
The entry is really difficult to translate, as word order changes for different languages: https://github.com/Yoast/License-Manager/blob/master/class-theme-update-manager.php#L101

It'd be good to:
* Change variables from `%s` to `%1$s`, `%2$s`..., so it becomes easier to localize
* Add translator help, defining what each translation means.

### PR DESCRIPTION
**Pull request by xavivars**
Fixes #66

### CODE REVIEW

**Comment by Rarst** [comment]
Could you please open PR from the dedicated branch? This will get messed up if you push anything more to master in your repo.

**Comment by xavivars** [comment]
I was planing to delete my full repo once this merge was done, but I can do that anyway

**Comment by xavivars** [comment]
Closed. Created PR #68 instead

**Comment by xavivars** [comment]
@Rarst, could you take a look to #68? Still open

**Pull request closed without merging**
