### PR TITLE
Use an extension url for linking to the license extend page.

### PR DESCRIPTION
**Pull request by andizer**
When the license is expired or almost expired we want to refer the user to another page than the product page. This pull request is adding this url.

### CODE REVIEW

**Comment by terw-dan** [comment]
CR done 👍

**Comment by boblinthorst** [comment]
Test-instructions are missing :/

**Comment by boblinthorst** [comment]
I seem to get an error: 
Error: Call to undefined method WPSEO_Product_Premium::extension_url() in /srv/www/wordpress-default/wp-content/plugins/wordpress-seo-premium/vendor/yoast/license-manager/class-product.php on line 291

If you can reproduce this error, try to fix this. If you cannot, feel free to place it in needs acceptance again, as I'm not 100% sure my setup matches the end result.

**Comment by terw-dan** [comment]
Acceptance: I don't seem to get a link to the extension URL, but to this page: https://yoast.com/wordpress/plugins/seo/#utm_campaign=Yoast+SEO+Premium+licensing&utm_medium=link&utm_source=Yoast+SEO+Premium&utm_content=license-expired-notice

Also, the page opens in the same tab, adding a `target=_blank` would seem appropriate to me, since you don't want the user to leave the admin.

**Comment by atimmer** [comment]
CR Done 👍🏻

**Comment by atimmer** [comment]
Acceptance done 👍🏻

**Pull request merged**
